repos:
    - repo: local
      hooks:
          - id: ruff
            name: ruff check
            entry: make lint-all
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: mypy
            name: mypy strict check
            entry: make typing-all
            language: system
            types: [python]
            pass_filenames: false
            always_run: true
            
          - id: pytest
            name: pytest
            entry: make tests-all
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: commitizen
            name: commitizen check
            entry: uv run cz check --commit-msg-file
            language: system
            pass_filenames: true
            stages: [commit-msg]

          - id: version-dry-run
            name: preview next version
            entry: make version-dry-run
            language: system
            pass_filenames: false
            always_run: true
            stages: [post-commit]
