services:
  init-secrets:
    image: alpine:${ALPINE_IMAGE_TAG:-3.22.4}
    profiles: ["init"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'
        reservations:
          cpus: '1'
          memory: '128M'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - extranet
    volumes:
      - ./secrets:/secrets
      - ./docker/init-secrets/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["sh", "/entrypoint.sh"]